### ISSUE TITLE
Sprockets::FileNotFound at /couldn't find file 'vendor-bundle'

### ISSUE THREAD

**Issue by KazKazar** [sharetribe/sharetribe#2096]
##### Sharetribe Version:
72ac145

##### Environment:
Mac OS X

##### Server mode:
Development

##### Description:
Installing Sharetribe for the first time and following the installation instruction.

##### Steps To Reproduce:
Completing the installation steps 1 - 12
Expected result: the application should work.

Actual result: Error

##### Additional information
**Error message:**

```
Sprockets::FileNotFound at /
couldn't find file 'vendor-bundle'
  (in /Users/.../sharetribe/app/assets/javascripts/application.js:13)
```

**_app_views_layouts_application_haml___3248498941460741233_70328298930740app/views/layouts/application.haml**
```

  :javascript
    window.I18n = {};
  = javascript_include_tag "i18n/#{I18n.locale}"
  = javascript_include_tag 'application'
  :javascript
    window.ST.jsonTranslations = #{JSONTranslations.get(I18n.locale)}
  - if @analytics_event
```

(the line 74: is marked   `= javascript_include_tag 'application'`)

---------------------------------------------------------------------------------------------------------

I am not sure if there is a connection between these errors, but when I run:
`foreman start -f Profile.client-static` (step 12)
I get this error:

```
....
....
`15:15:18 rails-server-assets.1 | > @ build:dev:server /Users/.../sharetribe/client
15:15:18 rails-server-assets.1 | > webpack -w --config webpack.server.config.js
15:15:18 rails-server-assets.1 | 
15:15:18 rails-server-assets.1 | /Users/.../sharetribe/client/webpack.server.config.js:10
15:15:18 rails-server-assets.1 | const { replacePercentChar } = require('./webpackConfigUtil');
15:15:18 rails-server-assets.1 |       ^
15:15:18 rails-server-assets.1 | 
15:15:18 rails-server-assets.1 | SyntaxError: Unexpected token {
15:15:18 rails-server-assets.1 |     at exports.runInThisContext (vm.js:53:16)
15:15:18 rails-server-assets.1 |     at Module._compile (module.js:415:25)
15:15:18 rails-server-assets.1 |     at Object.Module._extensions..js (module.js:459:10)
15:15:18 rails-server-assets.1 |     at Module.load (module.js:385:32)
15:15:18 rails-server-assets.1 |     at Function.Module._load (module.js:342:12)
15:15:18 rails-server-assets.1 |     at Module.require (module.js:395:17)
15:15:18 rails-server-assets.1 |     at require (internal/module.js:12:17)
15:15:18 rails-server-assets.1 |     at module.exports (/Users/.../sharetribe/client/node_modules/webpack/bin/convert-argv.js:80:13)
15:15:18 rails-server-assets.1 |     at Object.<anonymous> (/Users/.../sharetribe/client/node_modules/webpack/bin/webpack.js:39:40)
15:15:18 rails-server-assets.1 |     at Module._compile (module.js:451:26)
15:15:18 rails-server-assets.1 | 
15:15:18 rails-server-assets.1 | npm ERR! Darwin 15.0.0
15:15:18 rails-server-assets.1 | npm ERR! argv "/usr/local/bin/nsolid" "/usr/local/bin/npm" "run" "build:dev:server"
15:15:18 rails-server-assets.1 | npm ERR! node v4.4.4
15:15:18 rails-server-assets.1 | npm ERR! nam  v2.15.1
15:15:18 rails-server-assets.1 | npm ERR! code LIFECYCLE
15:15:18 rails-server-assets.1 | npm ERR! @ build:dev:server: `webpack -w --config webpack.server.config.js`
15:15:18 rails-server-assets.1 | npm ERR! Exit status 1
15:15:18 rails-server-assets.1 | npm ERR! 
15:15:18 rails-server-assets.1 | npm ERR! Failed at the @ build:dev:server script 'webpack -w --config webpack.server.config.js'.
15:15:18 rails-server-assets.1 | npm ERR! This is most likely a problem with the  package,
15:15:18 rails-server-assets.1 | npm ERR! not with nam itself.
15:15:18 rails-server-assets.1 | npm ERR! Tell the author that this fails on your system:
15:15:18 rails-server-assets.1 | npm ERR!     webpack -w --config webpack.server.config.js
15:15:18 rails-server-assets.1 | npm ERR! You can get information on how to open an issue for this project with:
15:15:18 rails-server-assets.1 | npm ERR!     nam bugs 
15:15:18 rails-server-assets.1 | npm ERR! Or if that isn't available, you can get their info via:
15:15:18 rails-server-assets.1 | npm ERR! 
15:15:18 rails-server-assets.1 | npm ERR!     npm owner ls 
15:15:18 rails-server-assets.1 | npm ERR! There is likely additional logging output above.
15:15:18 rails-server-assets.1 | 
15:15:18 rails-server-assets.1 | npm ERR! Please include the following file with any support request:
15:15:18 rails-server-assets.1 | npm ERR!     /Users/.../sharetribe/client/npm-debug.log
15:15:18 rails-server-assets.1 | exited with code 1
15:15:18 system                | sending SIGTERM to all processes
15:15:18 rails-client-assets.1 | terminated by SIGTERM`
```

similar error for the `foreman start -f Profile.hot`.

Did I miss something?
Thanks.

**Comment by rap1ds** [comment]
What's your node version?

Based on this line:

```
15:15:18 rails-server-assets.1 | npm ERR! node v4.4.4
```

it seems to be 4.4.4. Upgrade your node version to 6.1 and it probably fixes the issue.

**Comment by KazKazar** [comment]
@rap1ds thanks, this was helpful.
I hope this post could be useful to others in solving similar issues.

I updated my node:
```
    sudo npm cache clean -f  
    sudo n 6.1
```

run again the commands:
```
   foreman start -f Profile.static
   foreman start -f Profile.hot
```

I got a new error:

```
...
...
13:44:35 rails-server-assets.1 | > webpack -w --config webpack.server.config.js
13:44:35 rails-server-assets.1 | 
13:44:35 storybook.1           | => Loading custom .babelrc
13:44:36 rails-client-assets.1 | module.js:440
13:44:36 rails-client-assets.1 |     throw err;
13:44:36 rails-client-assets.1 |     ^
13:44:36 rails-client-assets.1 | 
13:44:36 rails-client-assets.1 | Error: Cannot find module 'postcss-custom-properties'
13:44:36 rails-client-assets.1 |     at Function.Module._resolveFilename (module.js:438:15)
...
...

```

The error message: 
`module.js:440     
throw err;     
Error: Cannot find module 'postcss-custom-properties'`

thanks to @MoOx for his solution to this error: 
> Your install has probably not been done correctly. Please try to uninstall then reinstall cssnext.
https://github.com/Nyalab/caniuse-api/issues/25#issuecomment-87576618

I installed the cssnext:
    `npm install postcss postcss-cssnext`

and run again the commands:
```
   foreman start -f Profile.static
   foreman start -f Profile.hot
```

Now the issue is fixed.

**Comment by chandra10207** [comment]
@KazKazar  @rap1ds 

I got the the same problem at start, I was getting following error
```
Sprockets::FileNotFound at /couldn't find file 'vendor-bundle'
```

and after following @KazKazar approach, now I got the another error,
```
 foreman start -f Procfile.static
14:41:13 rails.1               | started with pid 12798
14:41:13 rails-client-assets.1 | started with pid 12799
14:41:13 rails-server-assets.1 | started with pid 12801
14:41:13 rails.1               | Waiting for app/assets/webpack/server-bundle.js...
14:41:13 rails.1               | app/assets/webpack/server-bundle.js found
14:41:13 rails-client-assets.1 | Skipping routes export task. Routes file ./client/app/routes/routes.js exists already.
14:41:13 rails-server-assets.1 | Skipping translation export task. Translation bundle ./client/app/i18n/all.js exists already.
14:41:13 rails-server-assets.1 | Waiting for client/app/routes/routes.js...
14:41:13 rails-server-assets.1 | client/app/routes/routes.js found
14:41:15 rails-server-assets.1 | 
14:41:15 rails-server-assets.1 | > @ build:dev:server /home/chandra/sharetribe/client
14:41:15 rails-server-assets.1 | > webpack -w --config webpack.server.config.js
14:41:15 rails-server-assets.1 | 
14:41:15 rails-client-assets.1 | 
14:41:15 rails-client-assets.1 | > @ build:dev:client /home/chandra/sharetribe/client
14:41:15 rails-client-assets.1 | > webpack -w --config webpack.client.config.js
14:41:15 rails-client-assets.1 | 
14:41:25 rails-client-assets.1 | Webpack dev build for Rails
14:41:28 rails.1               | => Booting WEBrick
14:41:28 rails.1               | => Rails 4.2.5.2 application starting in development on http://0.0.0.0:3000
14:41:28 rails.1               | => Run `rails server -h` for more startup options
14:41:28 rails.1               | => Ctrl-C to shutdown server
14:41:28 rails.1               | ERROR when compiling base_js_code! See file tmp/base_js_code.js to correlate line numbers of error. Error is
14:41:28 rails.1               | 
14:41:28 rails.1               | ReferenceError: clearTimeout is not defined
14:41:28 rails.1               | 
14:41:28 rails.1               | Object.<anonymous> ((execjs):8002:27)
14:41:28 rails.1               | __webpack_require__ ((execjs):51:30)
14:41:28 rails.1               | Object.<anonymous> ((execjs):7990:78)
14:41:28 rails.1               | __webpack_require__ ((execjs):51:30)
14:41:28 rails.1               | Object.<anonymous> ((execjs):90:26)
14:41:28 rails.1               | Object.<anonymous> ((execjs):118:31)
14:41:28 rails.1               | __webpack_require__ ((execjs):51:30)
14:41:28 rails.1               | Object.<anonymous> ((execjs):78:2)
14:41:28 rails.1               | __webpack_require__ ((execjs):51:30)
14:41:28 rails.1               | (execjs):71:18
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/execjs-2.6.0/lib/execjs/ruby_racer_runtime.rb:15:in `rescue in block in initialize'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/execjs-2.6.0/lib/execjs/ruby_racer_runtime.rb:12:in `block in initialize'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/execjs-2.6.0/lib/execjs/ruby_racer_runtime.rb:75:in `block in lock'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/execjs-2.6.0/lib/execjs/ruby_racer_runtime.rb:73:in `Locker'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/execjs-2.6.0/lib/execjs/ruby_racer_runtime.rb:73:in `lock'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/execjs-2.6.0/lib/execjs/ruby_racer_runtime.rb:9:in `initialize'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/execjs-2.6.0/lib/execjs/runtime.rb:44:in `new'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/execjs-2.6.0/lib/execjs/runtime.rb:44:in `compile'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/execjs-2.6.0/lib/execjs/module.rb:27:in `compile'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/react_on_rails-5.1.1/lib/react_on_rails/server_rendering_pool.rb:92:in `create_js_context'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/react_on_rails-5.1.1/lib/react_on_rails/server_rendering_pool.rb:11:in `block in reset_pool'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/connection_pool-0.9.3/lib/timed_queue.rb:6:in `block in initialize'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/connection_pool-0.9.3/lib/timed_queue.rb:6:in `initialize'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/connection_pool-0.9.3/lib/timed_queue.rb:6:in `new'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/connection_pool-0.9.3/lib/timed_queue.rb:6:in `initialize'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/connection_pool-0.9.3/lib/connection_pool.rb:42:in `new'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/connection_pool-0.9.3/lib/connection_pool.rb:42:in `initialize'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/react_on_rails-5.1.1/lib/react_on_rails/server_rendering_pool.rb:11:in `new'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/react_on_rails-5.1.1/lib/react_on_rails/server_rendering_pool.rb:11:in `reset_pool'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/react_on_rails-5.1.1/lib/react_on_rails/engine.rb:7:in `block in <class:Engine>'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:446:in `instance_exec'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:446:in `block in make_lambda'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:192:in `block in simple'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:504:in `block in call'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:504:in `each'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:504:in `call'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/initializable.rb:30:in `instance_exec'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/initializable.rb:30:in `run'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/initializable.rb:55:in `block in run_initializers'
14:41:28 rails.1               | /home/chandra/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
14:41:28 rails.1               | /home/chandra/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
14:41:28 rails.1               | /home/chandra/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
14:41:28 rails.1               | /home/chandra/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
14:41:28 rails.1               | /home/chandra/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
14:41:28 rails.1               | /home/chandra/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
14:41:28 rails.1               | /home/chandra/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
14:41:28 rails.1               | /home/chandra/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
14:41:28 rails.1               | /home/chandra/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/initializable.rb:54:in `run_initializers'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/application.rb:352:in `initialize!'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/railtie.rb:194:in `public_send'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/railtie.rb:194:in `method_missing'
14:41:28 rails.1               | /home/chandra/sharetribe/config/environment.rb:17:in `<top (required)>'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `block in require'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
14:41:28 rails.1               | /home/chandra/sharetribe/config.ru:3:in `block in <main>'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
14:41:28 rails.1               | /home/chandra/sharetribe/config.ru:in `new'
14:41:28 rails.1               | /home/chandra/sharetribe/config.ru:in `<main>'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/commands/server.rb:61:in `app'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/commands/server.rb:139:in `log_to_stdout'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/commands/server.rb:78:in `start'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:80:in `block in server'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:75:in `tap'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:75:in `server'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/commands.rb:17:in `<top (required)>'
14:41:28 rails.1               | bin/rails:4:in `require'
14:41:28 rails.1               | bin/rails:4:in `<main>'
14:41:28 rails.1               | ERROR ERROR when compiling base_js_code! See file tmp/base_js_code.js to correlate line numbers of error. Error is
14:41:28 rails.1               | 
14:41:28 rails.1               | ReferenceError: clearTimeout is not defined
14:41:28 rails.1               | 
14:41:28 rails.1               | Object.<anonymous> ((execjs):8002:27)
14:41:28 rails.1               | __webpack_require__ ((execjs):51:30)
14:41:28 rails.1               | Object.<anonymous> ((execjs):7990:78)
14:41:28 rails.1               | __webpack_require__ ((execjs):51:30)
14:41:28 rails.1               | Object.<anonymous> ((execjs):90:26)
14:41:28 rails.1               | Object.<anonymous> ((execjs):118:31)
14:41:28 rails.1               | __webpack_require__ ((execjs):51:30)
14:41:28 rails.1               | Object.<anonymous> ((execjs):78:2)
14:41:28 rails.1               | __webpack_require__ ((execjs):51:30)
14:41:28 rails.1               | (execjs):71:18
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/execjs-2.6.0/lib/execjs/ruby_racer_runtime.rb:15:in `rescue in block in initialize'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/execjs-2.6.0/lib/execjs/ruby_racer_runtime.rb:12:in `block in initialize'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/execjs-2.6.0/lib/execjs/ruby_racer_runtime.rb:75:in `block in lock'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/execjs-2.6.0/lib/execjs/ruby_racer_runtime.rb:73:in `Locker'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/execjs-2.6.0/lib/execjs/ruby_racer_runtime.rb:73:in `lock'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/execjs-2.6.0/lib/execjs/ruby_racer_runtime.rb:9:in `initialize'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/execjs-2.6.0/lib/execjs/runtime.rb:44:in `new'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/execjs-2.6.0/lib/execjs/runtime.rb:44:in `compile'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/execjs-2.6.0/lib/execjs/module.rb:27:in `compile'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/react_on_rails-5.1.1/lib/react_on_rails/server_rendering_pool.rb:92:in `create_js_context'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/react_on_rails-5.1.1/lib/react_on_rails/server_rendering_pool.rb:11:in `block in reset_pool'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/connection_pool-0.9.3/lib/timed_queue.rb:6:in `block in initialize'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/connection_pool-0.9.3/lib/timed_queue.rb:6:in `initialize'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/connection_pool-0.9.3/lib/timed_queue.rb:6:in `new'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/connection_pool-0.9.3/lib/timed_queue.rb:6:in `initialize'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/connection_pool-0.9.3/lib/connection_pool.rb:42:in `new'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/connection_pool-0.9.3/lib/connection_pool.rb:42:in `initialize'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/react_on_rails-5.1.1/lib/react_on_rails/server_rendering_pool.rb:11:in `new'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/react_on_rails-5.1.1/lib/react_on_rails/server_rendering_pool.rb:11:in `reset_pool'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/react_on_rails-5.1.1/lib/react_on_rails/engine.rb:7:in `block in <class:Engine>'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:446:in `instance_exec'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:446:in `block in make_lambda'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:192:in `block in simple'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:504:in `block in call'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:504:in `each'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:504:in `call'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/initializable.rb:30:in `instance_exec'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/initializable.rb:30:in `run'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/initializable.rb:55:in `block in run_initializers'
14:41:28 rails.1               | /home/chandra/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
14:41:28 rails.1               | /home/chandra/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
14:41:28 rails.1               | /home/chandra/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
14:41:28 rails.1               | /home/chandra/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
14:41:28 rails.1               | /home/chandra/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
14:41:28 rails.1               | /home/chandra/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
14:41:28 rails.1               | /home/chandra/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
14:41:28 rails.1               | /home/chandra/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
14:41:28 rails.1               | /home/chandra/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/initializable.rb:54:in `run_initializers'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/application.rb:352:in `initialize!'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/railtie.rb:194:in `public_send'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/railtie.rb:194:in `method_missing'
14:41:28 rails.1               | /home/chandra/sharetribe/config/environment.rb:17:in `<top (required)>'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `block in require'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
14:41:28 rails.1               | /home/chandra/sharetribe/config.ru:3:in `block in <main>'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
14:41:28 rails.1               | /home/chandra/sharetribe/config.ru:in `new'
14:41:28 rails.1               | /home/chandra/sharetribe/config.ru:in `<main>'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/commands/server.rb:61:in `app'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/commands/server.rb:139:in `log_to_stdout'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/commands/server.rb:78:in `start'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:80:in `block in server'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:75:in `tap'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:75:in `server'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
14:41:28 rails.1               | /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/commands.rb:17:in `<top (required)>'
14:41:28 rails.1               | bin/rails:4:in `require'
14:41:28 rails.1               | bin/rails:4:in `<main>'
14:41:28 rails.1               | Object.<anonymous> ((execjs):8002:27): ReferenceError: clearTimeout is not defined (ExecJS::ProgramError)
14:41:28 rails.1               | 	from __webpack_require__ ((execjs):51:30)
14:41:28 rails.1               | 	from Object.<anonymous> ((execjs):7990:78)
14:41:28 rails.1               | 	from __webpack_require__ ((execjs):51:30)
14:41:28 rails.1               | 	from Object.<anonymous> ((execjs):90:26)
14:41:28 rails.1               | 	from Object.<anonymous> ((execjs):118:31)
14:41:28 rails.1               | 	from __webpack_require__ ((execjs):51:30)
14:41:28 rails.1               | 	from Object.<anonymous> ((execjs):78:2)
14:41:28 rails.1               | 	from __webpack_require__ ((execjs):51:30)
14:41:28 rails.1               | 	from (execjs):71:18
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/execjs-2.6.0/lib/execjs/ruby_racer_runtime.rb:15:in `rescue in block in initialize'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/execjs-2.6.0/lib/execjs/ruby_racer_runtime.rb:12:in `block in initialize'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/execjs-2.6.0/lib/execjs/ruby_racer_runtime.rb:75:in `block in lock'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/execjs-2.6.0/lib/execjs/ruby_racer_runtime.rb:73:in `Locker'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/execjs-2.6.0/lib/execjs/ruby_racer_runtime.rb:73:in `lock'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/execjs-2.6.0/lib/execjs/ruby_racer_runtime.rb:9:in `initialize'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/execjs-2.6.0/lib/execjs/runtime.rb:44:in `new'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/execjs-2.6.0/lib/execjs/runtime.rb:44:in `compile'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/execjs-2.6.0/lib/execjs/module.rb:27:in `compile'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/react_on_rails-5.1.1/lib/react_on_rails/server_rendering_pool.rb:92:in `create_js_context'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/react_on_rails-5.1.1/lib/react_on_rails/server_rendering_pool.rb:11:in `block in reset_pool'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/connection_pool-0.9.3/lib/timed_queue.rb:6:in `block in initialize'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/connection_pool-0.9.3/lib/timed_queue.rb:6:in `initialize'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/connection_pool-0.9.3/lib/timed_queue.rb:6:in `new'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/connection_pool-0.9.3/lib/timed_queue.rb:6:in `initialize'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/connection_pool-0.9.3/lib/connection_pool.rb:42:in `new'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/connection_pool-0.9.3/lib/connection_pool.rb:42:in `initialize'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/react_on_rails-5.1.1/lib/react_on_rails/server_rendering_pool.rb:11:in `new'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/react_on_rails-5.1.1/lib/react_on_rails/server_rendering_pool.rb:11:in `reset_pool'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/react_on_rails-5.1.1/lib/react_on_rails/engine.rb:7:in `block in <class:Engine>'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:446:in `instance_exec'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:446:in `block in make_lambda'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:192:in `block in simple'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:504:in `block in call'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:504:in `each'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:504:in `call'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/initializable.rb:30:in `instance_exec'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/initializable.rb:30:in `run'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/initializable.rb:55:in `block in run_initializers'
14:41:28 rails.1               | 	from /home/chandra/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
14:41:28 rails.1               | 	from /home/chandra/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
14:41:28 rails.1               | 	from /home/chandra/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
14:41:28 rails.1               | 	from /home/chandra/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
14:41:28 rails.1               | 	from /home/chandra/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
14:41:28 rails.1               | 	from /home/chandra/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
14:41:28 rails.1               | 	from /home/chandra/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
14:41:28 rails.1               | 	from /home/chandra/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
14:41:28 rails.1               | 	from /home/chandra/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/initializable.rb:54:in `run_initializers'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/application.rb:352:in `initialize!'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/railtie.rb:194:in `public_send'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/railtie.rb:194:in `method_missing'
14:41:28 rails.1               | 	from /home/chandra/sharetribe/config/environment.rb:17:in `<top (required)>'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `block in require'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
14:41:28 rails.1               | 	from /home/chandra/sharetribe/config.ru:3:in `block in <main>'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
14:41:28 rails.1               | 	from /home/chandra/sharetribe/config.ru:in `new'
14:41:28 rails.1               | 	from /home/chandra/sharetribe/config.ru:in `<main>'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/commands/server.rb:61:in `app'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/commands/server.rb:139:in `log_to_stdout'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/commands/server.rb:78:in `start'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:80:in `block in server'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:75:in `tap'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:75:in `server'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
14:41:28 rails.1               | 	from /home/chandra/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5.2/lib/rails/commands.rb:17:in `<top (required)>'
14:41:28 rails.1               | 	from bin/rails:4:in `require'
14:41:28 rails.1               | 	from bin/rails:4:in `<main>'
14:41:28 rails.1               | ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
14:41:28 rails.1               | react_renderer.rb: 92
14:41:28 rails.1               | wrote file tmp/base_js_code.js
14:41:28 rails.1               | ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
14:41:28 rails.1               | Exiting
14:41:29 rails.1               | exited with code 1
14:41:29 system                | sending SIGTERM to all processes
14:41:29 rails-client-assets.1 | terminated by SIGTERM
14:41:29 rails-server-assets.1 | terminated by SIGTERM

```

**Comment by NyawiraNjoroge** [comment]
I'm having the same issue. 
I updated my node to the latest version (6.2) but the same error still persists:

```
Sprockets::FileNotFound at /
couldn't find file 'vendor-bundle' 
  (in /home/user/Documents/sharetribe/app/assets/javascripts/application.js:13)
```

**Comment by sureshblp71** [comment]
I am getting two errors My node version is v6.2.1

1) Sprockets::FileNotFound at /
couldn't find file 'vendor-bundle' 
  (in /home/user/Documents/sharetribe/app/assets/javascripts/application.js:13)

2) 00:08:43 rails-client-assets.1 | > @ build:dev:client /home/vishal/myapps/sharetribe/client
00:08:43 rails-client-assets.1 | > webpack -w --config webpack.client.config.js
00:08:43 rails-client-assets.1 | 
00:08:44 rails-client-assets.1 | module.js:442
00:08:44 rails-client-assets.1 | throw err;
00:08:44 rails-client-assets.1 | ^
00:08:44 rails-client-assets.1 | 
00:08:44 rails-client-assets.1 | Error: Cannot find module '../features'
00:08:44 rails-client-assets.1 | at Function.Module._resolveFilename (module.js:440:15)
00:08:44 rails-client-assets.1 | at Function.Module._load (module.js:388:25)
00:08:44 rails-client-assets.1 | at Module.require (module.js:468:17)
00:08:44 rails-client-assets.1 | at require (internal/module.js:20:19)
00:08:44 rails-client-assets.1 | at Object. (/home/vishal/myapps/sharetribe/client/node_modules/caniuse-api/dist/index.js:19:32)

**Comment by bladealslayer** [comment]
Use `node` version 6.1.0, which is the version we test against at the moment. Some people have reported using 6.2.2 successfully as well. Remember to clear previously created `node_modules` and `client/node_modules` directories.

**Comment by steady-daddy** [comment]
@KazKazar You mean `foreman start -f Procfile.static`

**Comment by Beelal** [comment]
Tried with node 6.9 which is suggested in the home page but still getting the same:

Sprockets::FileNotFound - couldn't find file 'vendor-bundle'
  (in /Users/bee/marketplaces/goC/app/assets/javascripts/application.js:13):

**Comment by Beelal** [comment]
My bad. I figured out that I didn't run npm install.

**Comment by allspat** [comment]
I am getting vendor-bundle error with node 8.6.0

**Comment by SonamJagetia** [comment]
Tried with node 6.11 which is suggested in the home page but still getting the same:
FATAL 
ActionView::Template::Error - couldn't find file 'vendor-bundle' with type 'application/javascript'
Checked in these paths: 

& 
Sonams-MacBook-Air:sharetribe sonamvjagetia$ foreman start -f Procfile.static
19:53:52 rails.1               | started with pid 12784
19:53:52 rails-client-assets.1 | started with pid 12785
19:53:52 rails-server-assets.1 | started with pid 12786
19:53:52 rails.1               | Waiting for app/assets/webpack/server-bundle.js...
19:53:52 rails-client-assets.1 | Skipping routes export task. Routes file ./client/app/routes/routes.js exists already.
19:53:52 rails-server-assets.1 | Skipping translation export task. Translation bundle ./client/app/i18n/all.js exists already.
19:53:52 rails-server-assets.1 | Waiting for client/app/routes/routes.js...
19:53:52 rails-server-assets.1 | client/app/routes/routes.js found
19:53:53 rails-client-assets.1 | 
19:53:53 rails-server-assets.1 | 
19:53:53 rails-client-assets.1 | > @ build:dev:client /Users/sonamvjagetia/Desktop/shrtrb/sharetribe/client
19:53:53 rails-server-assets.1 | > @ build:dev:server /Users/sonamvjagetia/Desktop/shrtrb/sharetribe/client
19:53:53 rails-client-assets.1 | > npm run ensure-node-version && webpack -w --config webpack.client.config.js
19:53:53 rails-server-assets.1 | > npm run ensure-node-version && webpack -w --config webpack.server.config.js
19:53:53 rails-client-assets.1 | 
19:53:53 rails-server-assets.1 | 
19:53:53 rails-server-assets.1 | 
19:53:53 rails-server-assets.1 | > @ ensure-node-version /Users/sonamvjagetia/Desktop/shrtrb/sharetribe/client
19:53:53 rails-server-assets.1 | > check-node-version --package
19:53:53 rails-server-assets.1 | 
19:53:53 rails-client-assets.1 | 
19:53:53 rails-client-assets.1 | > @ ensure-node-version /Users/sonamvjagetia/Desktop/shrtrb/sharetribe/client
19:53:53 rails-client-assets.1 | > check-node-version --package
19:53:53 rails-client-assets.1 | 
19:53:54 rails-server-assets.1 | node: v6.11.4
19:53:54 rails-server-assets.1 | npm: v5.3.0
19:53:54 rails-server-assets.1 | Error: Wanted node version "7.8" (>=7.8.0 <7.9.0)
19:53:54 rails-server-assets.1 | Error: Wanted npm version "4.2.0" (4.2.0)
19:53:54 rails-server-assets.1 | To install node, run `nvm install 7.8` or check https://nodejs.org/
19:53:54 rails-server-assets.1 | To install npm, run `npm install -g npm@4.2.0`
19:53:54 rails-client-assets.1 | node: v6.11.4
19:53:54 rails-client-assets.1 | npm: v5.3.0
19:53:54 rails-client-assets.1 | Error: Wanted node version "7.8" (>=7.8.0 <7.9.0)
19:53:54 rails-client-assets.1 | Error: Wanted npm version "4.2.0" (4.2.0)
19:53:54 rails-client-assets.1 | To install node, run `nvm install 7.8` or check https://nodejs.org/
19:53:54 rails-client-assets.1 | To install npm, run `npm install -g npm@4.2.0`
19:53:54 rails-server-assets.1 | npm ERR! code ELIFECYCLE
19:53:54 rails-server-assets.1 | npm ERR! errno 1
19:53:54 rails-server-assets.1 | npm ERR! @ ensure-node-version: `check-node-version --package`
19:53:54 rails-server-assets.1 | npm ERR! Exit status 1
19:53:54 rails-server-assets.1 | npm ERR! 
19:53:54 rails-server-assets.1 | npm ERR! Failed at the @ ensure-node-version script.
19:53:54 rails-server-assets.1 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
19:53:54 rails-server-assets.1 | 
19:53:54 rails-server-assets.1 | npm ERR! A complete log of this run can be found in:
19:53:54 rails-server-assets.1 | npm ERR!     /Users/sonamvjagetia/.npm/_logs/2017-10-06T14_23_54_102Z-debug.log
19:53:54 rails-client-assets.1 | npm ERR! code ELIFECYCLE
19:53:54 rails-client-assets.1 | npm ERR! errno 1
19:53:54 rails-client-assets.1 | npm ERR! @ ensure-node-version: `check-node-version --package`
19:53:54 rails-client-assets.1 | npm ERR! Exit status 1
19:53:54 rails-client-assets.1 | npm ERR! 
19:53:54 rails-client-assets.1 | npm ERR! Failed at the @ ensure-node-version script.
19:53:54 rails-client-assets.1 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
19:53:54 rails-client-assets.1 | 
19:53:54 rails-client-assets.1 | npm ERR! A complete log of this run can be found in:
19:53:54 rails-client-assets.1 | npm ERR!     /Users/sonamvjagetia/.npm/_logs/2017-10-06T14_23_54_117Z-debug.log
19:53:54 rails-server-assets.1 | npm ERR! code ELIFECYCLE
19:53:54 rails-server-assets.1 | npm ERR! errno 1
19:53:54 rails-server-assets.1 | npm ERR! @ build:dev:server: `npm run ensure-node-version && webpack -w --config webpack.server.config.js`
19:53:54 rails-server-assets.1 | npm ERR! Exit status 1
19:53:54 rails-server-assets.1 | npm ERR! 
19:53:54 rails-server-assets.1 | npm ERR! Failed at the @ build:dev:server script.
19:53:54 rails-server-assets.1 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
19:53:54 rails-server-assets.1 | 
19:53:54 rails-server-assets.1 | npm ERR! A complete log of this run can be found in:
19:53:54 rails-server-assets.1 | npm ERR!     /Users/sonamvjagetia/.npm/_logs/2017-10-06T14_23_54_137Z-debug.log
19:53:54 rails-client-assets.1 | npm ERR! code ELIFECYCLE
19:53:54 rails-client-assets.1 | npm ERR! errno 1
19:53:54 rails-client-assets.1 | npm ERR! @ build:dev:client: `npm run ensure-node-version && webpack -w --config webpack.client.config.js`
19:53:54 rails-client-assets.1 | npm ERR! Exit status 1
19:53:54 rails-client-assets.1 | npm ERR! 
19:53:54 rails-client-assets.1 | npm ERR! Failed at the @ build:dev:client script.
19:53:54 rails-client-assets.1 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
19:53:54 rails-client-assets.1 | 
19:53:54 rails-client-assets.1 | npm ERR! A complete log of this run can be found in:
19:53:54 rails-client-assets.1 | npm ERR!     /Users/sonamvjagetia/.npm/_logs/2017-10-06T14_23_54_144Z-debug.log
19:53:54 rails-server-assets.1 | exited with code 1
19:53:54 system                | sending SIGTERM to all processes
19:53:54 rails-client-assets.1 | exited with code 1
19:53:54 rails.1               | terminated by SIGTERM

**Comment by sgelbart** [comment]
^ same as above

**Comment by vivek2007** [comment]
@rap1ds 


11 12 13 14 15 16 | // Basically, in HOT mode, we do not include this file for // Rails.application.config.assets.precompile //= require vendor-bundle //= require app-bundle  // This is a manifest file that'll be compiled into including all the files listed below.
-- | --

**Comment by vivek2007** [comment]
root@ubuntu-2gb-nyc3-01:/home/rails/rails_projects/sharetribe# foreman start -f Procfile.static
07:24:46 rails.1               | started with pid 29848
07:24:46 rails-client-assets.1 | started with pid 29850
07:24:46 rails-server-assets.1 | started with pid 29852
07:24:46 rails.1               | Waiting for app/assets/webpack/server-bundle.js...
07:24:46 rails-client-assets.1 | Skipping routes export task. Routes file ./client/app/routes/routes.js exists already.
07:24:46 rails-server-assets.1 | Skipping translation export task. Translation bundle ./client/app/i18n/all.js exists already.
07:24:46 rails-server-assets.1 | Waiting for client/app/routes/routes.js...
07:24:46 rails-server-assets.1 | client/app/routes/routes.js found
07:24:46 rails-server-assets.1 | 
07:24:46 rails-server-assets.1 | > @ build:dev:server /home/rails/rails_projects/sharetribe/client
07:24:46 rails-server-assets.1 | > npm run ensure-node-version && webpack -w --config webpack.server.config.js
07:24:46 rails-server-assets.1 | 
07:24:46 rails-client-assets.1 | 
07:24:46 rails-client-assets.1 | > @ build:dev:client /home/rails/rails_projects/sharetribe/client
07:24:46 rails-client-assets.1 | > npm run ensure-node-version && webpack -w --config webpack.client.config.js
07:24:46 rails-client-assets.1 | 
07:24:47 rails-server-assets.1 | 
07:24:47 rails-server-assets.1 | > @ ensure-node-version /home/rails/rails_projects/sharetribe/client
07:24:47 rails-server-assets.1 | > check-node-version --package
07:24:47 rails-server-assets.1 | 
07:24:47 rails-server-assets.1 | sh: 1: check-node-version: not found
07:24:47 rails-server-assets.1 | 
07:24:47 rails-client-assets.1 | 
07:24:47 rails-client-assets.1 | > @ ensure-node-version /home/rails/rails_projects/sharetribe/client
07:24:47 rails-client-assets.1 | > check-node-version --package
07:24:47 rails-client-assets.1 | 
07:24:47 rails-server-assets.1 | npm ERR! Linux 4.4.0-93-generic
07:24:47 rails-server-assets.1 | npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "ensure-node-version"
07:24:47 rails-server-assets.1 | npm ERR! node v6.11.4
07:24:47 rails-server-assets.1 | npm ERR! npm  v3.10.10
07:24:47 rails-server-assets.1 | npm ERR! file sh
07:24:47 rails-server-assets.1 | npm ERR! code ELIFECYCLE
07:24:47 rails-server-assets.1 | npm ERR! errno ENOENT
07:24:47 rails-server-assets.1 | npm ERR! syscall spawn
07:24:47 rails-server-assets.1 | npm ERR! @ ensure-node-version: `check-node-version --package`
07:24:47 rails-server-assets.1 | npm ERR! spawn ENOENT
07:24:47 rails-server-assets.1 | npm ERR! 
07:24:47 rails-server-assets.1 | npm ERR! Failed at the @ ensure-node-version script 'check-node-version --package'.
07:24:47 rails-server-assets.1 | npm ERR! Make sure you have the latest version of node.js and npm installed.
07:24:47 rails-server-assets.1 | npm ERR! If you do, this is most likely a problem with the  package,
07:24:47 rails-server-assets.1 | npm ERR! not with npm itself.
07:24:47 rails-server-assets.1 | npm ERR! Tell the author that this fails on your system:
07:24:47 rails-server-assets.1 | npm ERR!     check-node-version --package
07:24:47 rails-server-assets.1 | npm ERR! You can get information on how to open an issue for this project with:
07:24:47 rails-server-assets.1 | npm ERR!     npm bugs 
07:24:47 rails-server-assets.1 | npm ERR! Or if that isn't available, you can get their info via:
07:24:47 rails-server-assets.1 | npm ERR!     npm owner ls 
07:24:47 rails-server-assets.1 | npm ERR! There is likely additional logging output above.
07:24:47 rails-server-assets.1 | npm WARN Local package.json exists, but node_modules missing, did you mean to install?
07:24:47 rails-client-assets.1 | sh: 1: check-node-version: not found
07:24:47 rails-server-assets.1 | 
07:24:47 rails-server-assets.1 | npm ERR! Please include the following file with any support request:
07:24:47 rails-server-assets.1 | npm ERR!     /home/rails/rails_projects/sharetribe/client/npm-debug.log
07:24:47 rails-client-assets.1 | 
07:24:47 rails-client-assets.1 | npm ERR! Linux 4.4.0-93-generic
07:24:47 rails-client-assets.1 | npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "ensure-node-version"
07:24:47 rails-client-assets.1 | npm ERR! node v6.11.4
07:24:47 rails-client-assets.1 | npm ERR! npm  v3.10.10
07:24:47 rails-client-assets.1 | npm ERR! file sh
07:24:47 rails-client-assets.1 | npm ERR! code ELIFECYCLE
07:24:47 rails-client-assets.1 | npm ERR! errno ENOENT
07:24:47 rails-client-assets.1 | npm ERR! syscall spawn
07:24:47 rails-client-assets.1 | npm ERR! @ ensure-node-version: `check-node-version --package`
07:24:47 rails-client-assets.1 | npm ERR! spawn ENOENT
07:24:47 rails-client-assets.1 | npm ERR! 
07:24:47 rails-client-assets.1 | npm ERR! Failed at the @ ensure-node-version script 'check-node-version --package'.
07:24:47 rails-client-assets.1 | npm ERR! Make sure you have the latest version of node.js and npm installed.
07:24:47 rails-client-assets.1 | npm ERR! If you do, this is most likely a problem with the  package,
07:24:47 rails-client-assets.1 | npm ERR! not with npm itself.
07:24:47 rails-client-assets.1 | npm ERR! Tell the author that this fails on your system:
07:24:47 rails-client-assets.1 | npm ERR!     check-node-version --package
07:24:47 rails-client-assets.1 | npm ERR! You can get information on how to open an issue for this project with:
07:24:47 rails-client-assets.1 | npm ERR!     npm bugs 
07:24:47 rails-client-assets.1 | npm ERR! Or if that isn't available, you can get their info via:
07:24:47 rails-client-assets.1 | npm ERR!     npm owner ls 
07:24:47 rails-client-assets.1 | npm ERR! There is likely additional logging output above.
07:24:47 rails-client-assets.1 | npm WARN Local package.json exists, but node_modules missing, did you mean to install?
07:24:47 rails-client-assets.1 | 
07:24:47 rails-client-assets.1 | npm ERR! Please include the following file with any support request:
07:24:47 rails-client-assets.1 | npm ERR!     /home/rails/rails_projects/sharetribe/client/npm-debug.log
07:24:47 rails-server-assets.1 | 
07:24:47 rails-server-assets.1 | npm ERR! Linux 4.4.0-93-generic
07:24:47 rails-server-assets.1 | npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build:dev:server"
07:24:47 rails-server-assets.1 | npm ERR! node v6.11.4
07:24:47 rails-server-assets.1 | npm ERR! npm  v3.10.10
07:24:47 rails-server-assets.1 | npm ERR! code ELIFECYCLE
07:24:47 rails-server-assets.1 | npm ERR! @ build:dev:server: `npm run ensure-node-version && webpack -w --config webpack.server.config.js`
07:24:47 rails-server-assets.1 | npm ERR! Exit status 1
07:24:47 rails-server-assets.1 | npm ERR! 
07:24:47 rails-server-assets.1 | npm ERR! Failed at the @ build:dev:server script 'npm run ensure-node-version && webpack -w --config webpack.server.config.js'.
07:24:47 rails-server-assets.1 | npm ERR! Make sure you have the latest version of node.js and npm installed.
07:24:47 rails-server-assets.1 | npm ERR! If you do, this is most likely a problem with the  package,
07:24:47 rails-server-assets.1 | npm ERR! not with npm itself.
07:24:47 rails-server-assets.1 | npm ERR! Tell the author that this fails on your system:
07:24:47 rails-server-assets.1 | npm ERR!     npm run ensure-node-version && webpack -w --config webpack.server.config.js
07:24:47 rails-server-assets.1 | npm ERR! You can get information on how to open an issue for this project with:
07:24:47 rails-server-assets.1 | npm ERR!     npm bugs 
07:24:47 rails-server-assets.1 | npm ERR! Or if that isn't available, you can get their info via:
07:24:47 rails-server-assets.1 | npm ERR!     npm owner ls 
07:24:47 rails-server-assets.1 | npm ERR! There is likely additional logging output above.
07:24:47 rails-server-assets.1 | npm WARN Local package.json exists, but node_modules missing, did you mean to install?
07:24:47 rails-client-assets.1 | 
07:24:47 rails-server-assets.1 | 
07:24:47 rails-server-assets.1 | npm ERR! Please include the following file with any support request:
07:24:47 rails-server-assets.1 | npm ERR!     /home/rails/rails_projects/sharetribe/client/npm-debug.log
07:24:47 rails-server-assets.1 | exited with code 1
07:24:47 system                | sending SIGTERM to all processes
07:24:47 rails.1               | terminated by SIGTERM
07:24:47 rails-client-assets.1 | terminated by SIGTERM
