### ISSUE TITLE
Admin mail confirmation not sent

### ISSUE THREAD

**Issue by LeoMartinDev** [sharetribe/sharetribe#2695]
##### Environment: Ubuntu 16.06

node -v 6.9.1
node -v 3.10.9

**Comment by rap1ds** [comment]
Please give more information, otherwise we are not able to help.

Have you configured your STMP settings? Are you able to send any other emails? Do you have background worker running? What are the exact steps to reproduce the issue?

**Comment by shoaibmalik786** [comment]
Hi @rap1ds - 
I have setup the smtp settings, i am getting other emails like, forgot password email etc. but not getting email confirmation email, could you please help me to find out what is the issue exactly?

Thanks

**Comment by ckaehler** [comment]
Hi @rap1ds and @shoaibmalik786,

we are suddenly experiencing the same problem. All emails are being sent except the email confirmation for new members. Moreover, the /confirmation_pending is skipped all of a sudden. 

Expected user flow is this:
1. Register
2. Get to /confirmation_pending page
3. Receive confirmation email, click on confirm
4. Get to marketplace
5. Receives welcome email

Actual user flow is this:
1. Register
2. Get to marketplace
3. Receives welcome email

This to give you some details from the product manager point of view ;)

**Comment by LeoMartinDev** [comment]
Here's the error :

`[Worker(host:leo-GS60-6QE pid:25557)] Job EmailConfirmationJob (id=4) FAILED (1 prior attempts) with EOFError: end of file reached`

**Comment by rap1ds** [comment]
@LeoMartinDev @ckaehler @shoaibmalik786 Thanks all for the information.

Have you changed the configuration of `skip_email_confirmation` config variable? What's the value for that variable in your setup? If you have changed it, have you changed it by changing the `config.yml` file or have you changed it by setting `skip_email_configuration` environment variable?

**Comment by LeoMartinDev** [comment]
I solve my issue in reinstalling `sendmail`.

**Comment by rap1ds** [comment]
Inactive. Closing.

**Comment by chdezmar** [comment]
Same issue here. New users are not getting the confirmation email and we are not getting an error. Not sure how to reinstall `sendmail`.

**Comment by kaoboyandy** [comment]
@rap1ds  Regarding your previous comment: "If you have changed it, have you changed it by changing the config.yml file or have you changed it by setting skip_email_configuration environment variable?" Which one is the right approach? Confirmation email not working on our end too.

**Comment by rap1ds** [comment]
@kaoboyandy Both are fine. You can change configuration by editing the `config.yml` file or via environment variable.

The application tries to look for a configuration value in the following order:

1. Environment variables
2. `config.yml`
3. `config.defaults.yml`

**Comment by kaoboyandy** [comment]
@rap1ds Thanks for your reply! 
In that case, we've already changed <skip_email_confirmation> to <FALSE> but the signup confirmation still isn't working, not sure if you could shed some light on where to dig further?

**Comment by karibuTW** [comment]
Same error here...
Any solution?

**Comment by vivek2007** [comment]
Hi @rap1ds 
I added following lines in config.default.yml
  mail_delivery_method: sendmail

   smtp_email_address: "smtp.gmail.com"
   smtp_email_port: 587
   smtp_email_user_name: "test@gmail.com"
   smtp_email_password: "t"est
   smtp_email_domain: "localhost"


and added following lines in production.rb

  if mail_delivery_method == :smtp
    ActionMailer::Base.smtp_settings = {
      :address              => "smtp.gmail.com",
      :port                 => "587",
      :domain               => "gmail.com",
      :user_name            => "test@gmail.com",
      :password             => "test",
      :authentication       => 'plain',
      :enable_starttls_auto => true
    }
  end


But still unable receive after signup confirmation

**Comment by vasaf** [comment]
Hey @vivek2007 
Did you manage to fix your issue with mailing?

Iv'e run into the same trouble as you now, and can't seem to solve it.

Thanks.

**Comment by vivek2007** [comment]
@vasaf
Yes i fixed it for my clients

**Comment by vivek2007** [comment]
@vasaf 
Catch me @skype baaaby2007

**Comment by shantilal-narola** [comment]
@vivek2007, Can you please share your solution? I'm running into the same issue.

**Comment by ervinismu** [comment]
I have changed it but it still doesn't work, any solution? @shantilal-narola @rap1ds
