### ISSUE TITLE
Node Sass could not find a binding for your current environment

### ISSUE THREAD

**Issue by aniketstiwari** [sharetribe/sharetribe#3090]
When I am trying to run foreman start -f Procfile.static
I am getting this error

ERROR in Missing binding /home/aniketshivamtiwari/sharetribe/client/node_modules/node-sass/vendor/linux-x64-51/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 7.x
Found bindings for the following environments:
- Linux 64-bit with Unsupported runtime (57)

Even I tried running npm rebuild node-sass but it didn't work for me

**Comment by thomasmalbaux** [comment]
Thanks for reporting, @aniketstiwari!

I've experienced the same issue and running `npm rebuild node-sass` apparently didn't help. I actually did it a couple times and also ran again `bundle install` and `npm install`.

Then I tried again to run `foreman start -f Procfile.static` and I've waited a couple minutes: it seemed stuck for a moment but then it just worked smoothly, even though the error was still visible.

It might mean that some elements (relying on React) may not work correctly, so this doesn't mean that the issue is solved however I'd like to hear if waiting for a little while generates the same result for you.

Could you try and let us know?

Learning a bit more about your environment would also be intersting.

_What's your environment? Mac OS X, Heroku, Linux, Windows Linux Subsystem or something else?_

_What's your node version? Run the following commands and copy the result here:_

```
> node -v
> npm -v
```

**Comment by aniketstiwari** [comment]
Thanks for replying
When running foreman start -f Procfile.static and hitting http://lvh.me:3000/ still getting same error. As you said wait for couple minutes but it didn't work.
**My environment 
Ubuntu 16.04
node -v
v7.8.0
npm -v
4.2.0**

**Comment by xuanus** [comment]
1. rm node_modules
2 rebuild node-sass

**Comment by thomasmalbaux** [comment]
Thanks for sharing those tips, @xuanus. This helped in my case.

Even with the error displayed, I was earlier able to load the page at http://localhost:3000 (or http://localhost:5000 based on your configuration) and things we working smoothly.

Now, after removing all node_modules and installing them again the error message no longer appears and things work fine also.

@aniketstiwari, do you experience the same?

**Comment by aniketstiwari** [comment]
Hi,  Actually I was doing a very silly mistake. I was trying to run this http://lvh.me:3000/ which was giving me an error. But when I check the terminal it was saying to run on port 5000. So when I tried http://lvh.me:5000/ it starts working. I want to know these error messages which I am getting should i ignore it or not

foreman start -f Procfile.static
15:45:57 rails.1               | started with pid 15897
15:45:57 rails-client-assets.1 | started with pid 15898
15:45:57 rails-server-assets.1 | started with pid 15901
15:45:57 rails-client-assets.1 | Exporting routes...
15:45:57 rails-server-assets.1 | Exporting translations...
15:45:57 rails.1               | Waiting for app/assets/webpack/server-bundle.js...
15:46:04 rails-client-assets.1 | Routes exported to ./client/app/routes/routes.js
15:46:06 rails-client-assets.1 | 
15:46:06 rails-client-assets.1 | > @ build:dev:client /home/aniketshivamtiwari/sharetribe/client
15:46:06 rails-client-assets.1 | > npm run ensure-node-version && webpack -w --config webpack.client.config.js
15:46:06 rails-client-assets.1 | 
15:46:06 rails-client-assets.1 | 
15:46:06 rails-client-assets.1 | > @ ensure-node-version /home/aniketshivamtiwari/sharetribe/client
15:46:06 rails-client-assets.1 | > check-node-version --package
15:46:06 rails-client-assets.1 | 
15:46:07 rails-client-assets.1 | node: v7.8.0
15:46:07 rails-client-assets.1 | npm: v4.2.0
15:46:08 rails-server-assets.1 | Translations exported to ./client/app/i18n/all.js
15:46:08 rails-server-assets.1 | Waiting for client/app/routes/routes.js...
15:46:08 rails-server-assets.1 | client/app/routes/routes.js found
15:46:08 rails-server-assets.1 | 
15:46:08 rails-server-assets.1 | > @ build:dev:server /home/aniketshivamtiwari/sharetribe/client
15:46:08 rails-server-assets.1 | > npm run ensure-node-version && webpack -w --config webpack.server.config.js
15:46:08 rails-server-assets.1 | 
15:46:09 rails-server-assets.1 | 
15:46:09 rails-server-assets.1 | > @ ensure-node-version /home/aniketshivamtiwari/sharetribe/client
15:46:09 rails-server-assets.1 | > check-node-version --package
15:46:09 rails-server-assets.1 | 
15:46:09 rails-server-assets.1 | node: v7.8.0
15:46:09 rails-server-assets.1 | npm: v4.2.0
15:46:09 rails-client-assets.1 | Webpack dev build for Rails
15:46:25 rails-server-assets.1 | Asset ["step3_coverPhoto.jpg"] is copied to /home/aniketshivamtiwari/sharetribe/public/webpack/step3_coverPhoto-875d69d62fde8885b67184f8cdc5ac45.jpg
15:46:25 rails-server-assets.1 | Asset ["step2_sloganDescription.jpg"] is copied to /home/aniketshivamtiwari/sharetribe/public/webpack/step2_sloganDescription-a83c0c2cb462753018c9650b1215c4f9.jpg
15:46:25 rails-server-assets.1 | Asset ["step6_addListing.jpg"] is copied to /home/aniketshivamtiwari/sharetribe/public/webpack/step6_addListing-95c1db46186bcf7e7e93366347b92103.jpg
15:46:25 rails-server-assets.1 | Asset ["step4_fieldsFilters.jpg"] is copied to /home/aniketshivamtiwari/sharetribe/public/webpack/step4_fieldsFilters-4203c725b71275066cab9884795775f0.jpg
15:46:25 rails-server-assets.1 | Hash: 837567688b24bd9db9a7
15:46:25 rails-server-assets.1 | Version: webpack 1.13.3
15:46:25 rails-server-assets.1 | Time: 15753ms
15:46:25 rails-server-assets.1 |            Asset     Size  Chunks             Chunk Names
15:46:25 rails-server-assets.1 | server-bundle.js  3.87 MB       0  [emitted]  main
15:46:25 rails-server-assets.1 |    [0] multi main 40 bytes {0} [built]
15:46:25 rails-server-assets.1 |  [650] ./app/i18n/all.js 380 kB {0} [optional] [built]
15:46:25 rails-server-assets.1 |  [653] ./app/routes/routes.js 146 kB {0} [optional] [built]
15:46:25 rails-server-assets.1 |     + 1010 hidden modules
15:46:25 rails.1               | app/assets/webpack/server-bundle.js found
15:46:27 rails-client-assets.1 | Asset ["step3_coverPhoto.jpg"] is copied to /home/aniketshivamtiwari/sharetribe/public/webpack/step3_coverPhoto-875d69d62fde8885b67184f8cdc5ac45.jpg
15:46:27 rails-client-assets.1 | Asset ["step2_sloganDescription.jpg"] is copied to /home/aniketshivamtiwari/sharetribe/public/webpack/step2_sloganDescription-a83c0c2cb462753018c9650b1215c4f9.jpg
15:46:27 rails-client-assets.1 | Asset ["step4_fieldsFilters.jpg"] is copied to /home/aniketshivamtiwari/sharetribe/public/webpack/step4_fieldsFilters-4203c725b71275066cab9884795775f0.jpg
15:46:27 rails-client-assets.1 | Asset ["step6_addListing.jpg"] is copied to /home/aniketshivamtiwari/sharetribe/public/webpack/step6_addListing-95c1db46186bcf7e7e93366347b92103.jpg
15:46:30 rails-client-assets.1 | Hash: 68bbcecbdcdb76cbf7bf
15:46:30 rails-client-assets.1 | Version: webpack 1.13.3
15:46:30 rails-client-assets.1 | Time: 20535ms
15:46:30 rails-client-assets.1 |            Asset     Size  Chunks             Chunk Names
15:46:30 rails-client-assets.1 |    app-bundle.js  8.82 MB       0  [emitted]  app
15:46:30 rails-client-assets.1 | vendor-bundle.js   408 kB       1  [emitted]  vendor
15:46:30 rails-client-assets.1 |   app-bundle.css  74.9 kB       0  [emitted]  app
15:46:30 rails-client-assets.1 |    [0] multi app 28 bytes {0} [built]
15:46:30 rails-client-assets.1 |    [0] multi vendor 40 bytes {1} [built]
15:46:30 rails-client-assets.1 |  [300] ./app/routes/routes.js 146 kB {0} [optional] [built]
15:46:30 rails-client-assets.1 |     + 711 hidden modules
15:46:30 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:46:30 rails-client-assets.1 |         + 2 hidden modules
15:46:30 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:46:30 rails-client-assets.1 |         + 2 hidden modules
15:46:30 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:46:30 rails-client-assets.1 |         + 2 hidden modules
15:46:30 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:46:30 rails-client-assets.1 |         + 2 hidden modules
15:46:30 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:46:30 rails-client-assets.1 |         + 2 hidden modules
15:46:30 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:46:30 rails-client-assets.1 |         + 2 hidden modules
15:46:30 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:46:30 rails-client-assets.1 |         + 2 hidden modules
15:46:30 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:46:30 rails-client-assets.1 |         + 2 hidden modules
15:46:30 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:46:30 rails-client-assets.1 |         + 2 hidden modules
15:46:30 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:46:30 rails-client-assets.1 |         + 2 hidden modules
15:46:30 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:46:30 rails-client-assets.1 |         + 2 hidden modules
15:46:30 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:46:30 rails-client-assets.1 |         + 2 hidden modules
15:46:30 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:46:30 rails-client-assets.1 |         + 2 hidden modules
15:46:30 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:46:30 rails-client-assets.1 |         + 2 hidden modules
15:46:30 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:46:30 rails-client-assets.1 |         + 2 hidden modules
15:46:30 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:46:30 rails-client-assets.1 |         + 2 hidden modules
15:46:30 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:46:30 rails-client-assets.1 |         + 2 hidden modules
15:46:30 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:46:30 rails-client-assets.1 |         + 2 hidden modules
15:46:30 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:46:30 rails-client-assets.1 |         + 2 hidden modules
15:46:30 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:46:30 rails-client-assets.1 |         + 2 hidden modules
15:46:30 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:46:30 rails-client-assets.1 |         + 2 hidden modules
15:46:30 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:46:30 rails-client-assets.1 |         + 2 hidden modules
15:46:30 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:46:30 rails-client-assets.1 |         + 2 hidden modules
15:46:30 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:46:30 rails-client-assets.1 |         + 2 hidden modules
15:46:30 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:46:30 rails-client-assets.1 |         + 2 hidden modules
15:46:30 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:46:30 rails-client-assets.1 |         + 4 hidden modules
15:46:30 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:46:30 rails-client-assets.1 |         + 2 hidden modules
15:46:30 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:46:30 rails-client-assets.1 |         + 2 hidden modules
15:46:30 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:46:30 rails-client-assets.1 |         + 2 hidden modules

**Comment by thomasmalbaux** [comment]
All right, good to hear that the 5000 port helped also!

Keep up the good work.

**Comment by Singh-KiaTec** [comment]
https://stackoverflow.com/a/49669424/9601544
